### ISSUE TITLE
Hardcode links for NTW collection page

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault#1138]
Determine the URLs for OV pages corresponding to the descriptions under http://main.wgbh.org/wgbh/NTW/FA/index.html, and make hardcoded html for the NTW collection page.

(Best grouping by tab has not been determined.)

(#1057, moving the finding aids referenced above to OV, has been filed, but I don't expect it to happen any time soon.)

**Comment by mccalluc** [comment]
There are 390 [title links](http://main.wgbh.org/wgbh/NTW/FA/TPN/TITLES.HTML), and 350 old slugs that begin with "ntw", so I'm going to start from that: Figure out the titles and how to group them ...

**Comment by Muraszko** [comment]
In progress, should have some xml files in April and will provide a list of <pbcoreIdentifier source="MD5" version="1"> (hand made UOI_IDs) to populate the page with.

**Comment by mccalluc** [comment]
@Muraszko : was this already done?

**Comment by Muraszko** [comment]
@mccalluc Yup!
