### ISSUE TITLE
Clean up "Rockefeller Artists-in-Television"

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault#1142]
"Rockefeller Artists-in-Television": There appear to be 3 series records currently, but two identical Artesia records may represent a "subseries"?
```xml
<pbcoreTitle titleType="Collection">New Television Workshop</pbcoreTitle>
<pbcoreTitle titleType="Series">Rockefeller Artists in Television</pbcoreTitle>
<pbcoreTitle titleType="Subseries">Rear Bumpers</pbcoreTitle>
``` 
- http://openvault.wgbh.org/catalog/mla000349-rockefeller-artists-in-television (Artesia)
- http://openvault.wgbh.org/catalog/openvault:52459 (Artesia, duplicate)

The remaining MARS record has related programs:
- http://openvault.wgbh.org/catalog/changeme:3687

The individual programs under the series also have duplicate records. For example, there are four records for "Royal Flesh". http://openvault.wgbh.org/catalog?q=royal+flesh. One is slugged: http://openvault.wgbh.org/catalog/ntw-mla000356-royal-flesh

**done when**
- There is one series record, which is slugged, and it is linked to programs.
- There is one program record for each program, and it is slugged.

**Comment by Muraszko** [comment]
Closing.
