### ISSUE TITLE
Forum Network link is dead for NTW

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault#1237]
`app/views/exhibits/new_television_workshop.html.erb` references `http://forum-network.org/fn-search/lectures?keys=new%20television%20workshop`: The link is dead.

We should go straight to http://forum-network.org/lectures/history-experimental-video-boston/ ... except there isn't actually any playable media there. Was there ever?

**Comment by Muraszko** [comment]
@mccalluc No, never any video.  Just an info page.  Yes, please link to that instead.
