### ISSUE TITLE
Broken Legacy URL Routing from Collection Pages

### ISSUE THREAD

**Issue by Muraszko** [WGBH/openvault#1255]
The collection pages that are pointing to records with legacy URLs appear to not be routing to their "openvault:1234" URLs.

@afred

**Comment by afred** [comment]
The index has currently lost all the `slug` fields, so attempts to look up docs by slug are 404-ing.

**NOTE** the records are still in the index, accessible at routes like `catalog/[id]`, where `[id]` is the Solr ID of the records. E.g. the "David Aaron" interview can be reached at http://openvault.wgbh.org/catalog/openvault:1318.

There are 2 instances of jetty on `lsopenvault01.wgbh.org`, one named `jetty_prod` and one named `jetty_staging`. I tried pointing the website to both, and got the same result.

**Comment by afred** [comment]
**Solution**

1. Symlink `openvault-staging/jetty` to `shared/jetty_staging`.
1. Test by...
  1. Restart Rails
  1. Do a search, and verify expected results
  1. Check exhibit link
1. Deploy latest code to `openvault-staging`. Capistrano should be able to do this easily.
1. Copy Rails app's jetty config to `shared/jetty_staging`. Might be able to do this with `RAILS_ENV=production bundle exec rake jetty:config`.
1. Repeat step 2
1. Re-run the scripts that add the slugs to solr docs. Need to figure out which these are, and what parameters are needed.
1. Repeat step 2 -- The exhibit links should be working.

**Comment by afred** [comment]
Fixed by re-running the slug setter script.

Unsure why we lost the slugs from the index. Continued mystery, but closing this ticket.
