### ISSUE TITLE
Make video pages with registration required look better

### ISSUE THREAD

**Issue by avatousiou** [WGBH/openvault#823]
The video player isn't rendering on these players and the red "Registration Required" text isn't formatting nicely with the rest of the page

(Example: http://openvault.wgbh.org/catalog/vietnam-eff033-eyewitness-our-war-in-vietnam)

**Comment by mccalluc** [comment]
Screen shot, for reference: http://openvault.wgbh.org/catalog/vietnam-06-338-refugee-camp
![screen shot 2015-05-27 at 1 07 36 pm](https://cloud.githubusercontent.com/assets/730388/7842535/b442822a-0471-11e5-9404-f2f3c4af44b9.png)
