### ISSUE TITLE
Implement Google Fonts

### ISSUE THREAD

**Issue by Muraszko** [WGBH/openvault#993]
LOW PRIORITY:
As per our discussion with Alison from Design, we need to modify the fonts at some point and her suggestion was to use Google Fonts.  There is a tutorial as to how to start to implement it here:
https://developers.google.com/fonts/docs/getting_started#Optimizing_Requests

If that's the best way to go about this.  

The scholar collection abstract details are able to be edited with html and I was successful in doing so, but it messed up the font for the entire page.  So it's possible to do there, but not the ideal solution.

**Comment by mccalluc** [comment]
@Muraszko : do you think we'll ever touch this? Could it be closed? My sense is that the fonts are the least of the design problems with OV.

**Comment by Muraszko** [comment]
@mccalluc Yeah, the plan changed.  Closing.
